name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - ActiveDirectoryService/* 

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: 'ActiveDirectoryService/projects/**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'ActiveDirectoryService/projects/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) /p:SolutionDir=$(Build.SourcesDirectory)/ActiveDirectoryService/ /p:LangVersion=latest' 
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'ActiveDirectoryService/projects/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
